### ISSUE TITLE
Include multistream destination bitrate on Stream Health dashboard

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#685] opened 2021-11-01 16:27 UTC
In our original spec of Stream Health, we discussed including multistream destination bitrate in the Session Ingest Rate graph. Something like this:

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/5bcc4bd7-059c-48f1-a7cd-63aeb0a07e9a)

With the recent changes in the stream health API, this is now possible!

Completing this will require input from @victorges for technical implementation as well as @adamsoffer for design.

**Comment by FullStackTiger** [comment] 2021-11-04 16:44
How to create mock data for this chart? and then where can I check the specific design?
@victorges @adamsoffer

**Comment by adamsoffer** [comment] 2021-11-04 17:21
Hey @FullStackTiger - here's the mock up in figma for the chart: https://www.figma.com/file/z09WhEiP7gopgNZ0QPuOB7/Dashboard?node-id=196%3A3657

@victorges think you can assist Vukasin with identifying the api hooks he needs to populate this chart?

![image](https://user-images.githubusercontent.com/555740/140388087-25fd3acc-2228-4aa4-a4c2-496cf2e4de95.png)

**Comment by victorges** [comment] 2021-11-04 21:06
Hey @FullStackTiger !

So the data is supposed to come from the Stream Health API. We are currently already using it for the `Health` tab on the dashboard, both for the stream healthchecks ([code](https://github.com/livepeer/livepeer-com/blob/9b12a1da82caf09b5d3ab6f65f706863e4cabaa0/packages/www/components/Dashboard/HealthChecksTable/index.tsx#L27)) as well as that log feed with status/errors ([code](https://github.com/livepeer/livepeer-com/blob/9c182a92c95c700ebd0ff78f9c8df8f3b94097b9/packages/www/components/Dashboard/Logger/index.tsx#L95)). I am just now writing some documentation on how to use that API on #695 ([you can preview it here](https://livepeer-com-git-vg-docsstream-health-api-livepeer.vercel.app/docs/guides/start-live-streaming/monitoring-stream-health#stream-health-api)).

For an E2E test/flow, you would have to:
 - Create a multistream target on your stream: [docs](https://livepeer.com/docs/guides/start-live-streaming/multistream)
 - Stream something to that stream. Can be done with ffmpeg, OBS, Streamlabs, stream-tester or any regular streaming software. LMK if you need help setting this up
 - Call the Stream Health API and grab the multistream metrics (something like `metrics.MultistreamBitrateSec[]`, one item for each multistream target (or maybe previous sessions, might be a corner case in the code))
 - On the actual code that builds the graph, keep calling that API periodically and build up the metric history locally. That because we currently don't offer an API to grab a list of values from the metric, only the last reading. 
 - You might not even need to call the API yourself, just receive the same argument as the `HealthChecksTable` that I linked above (I think your component should be really close to it in the hierarchy). That one should already be refreshed every 5 seconds (which should be enough for the graph, these metrics are only updated every 10 seconds).
 - So the code can only receive the stream health as argument and check if there are any new metrics on each health status (by timestamp and maybe value perhaps) and append to some local history. The current session ingest data is done very similarly if I'm not mistaken, it just comes from a different data source (the regular `/api`).

To facilitate your testing, I also just ran a stream and kept collecting the stream health data from it every second (probably gonna be some repeated values, but it's good cause you'll need to handle those in prod as well). Here it is: [multistream-metrics.zip](https://github.com/livepeer/livepeer-com/files/7478476/multistream-metrics.zip)

Let me know if anything is not clear or if you need any more help! We can continue chatting here, on discord or even just schedule some time to talk about it! Also count me in for any code review related to this 😄

**Comment by FullStackTiger** [comment] 2021-11-09 19:47
How to get the MultistreamBitrateSec data from /stream/${streamId}/health? I can't see MultistreamBitrateSec like this:
![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/c33f6bf1-902e-48af-b8d0-282517dfad0e)

1. Seems it can't add the streams to the Multistream Targets: it displays "pending" always.
![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/60810b3c-171b-41f8-8c30-ae9c7e885102)
- Actually the"second stream" is active, added this stream to the Multistream Targets, but "pending"
- I am using livepeer.monster API

Please check it kindly:
@victorges @adamsoffer @iameli

**Comment by victorges** [comment] 2021-11-09 23:21
Hey @FullStackTiger, sorry I only got some time now to dig deeper into your problem. It's really weird that you had that issue with your stream. I checked both your streams and the multistream target objects created in the API and everything seems perfectly fine. Also confirmed that, inspite of all that, there was no multistream data on Stream Health API. Also checked logs and could not find anything obvious.

So I tested multistreaming from one Livepeer stream from another, both in staging and in production, and had absolutely no issues. I then even tried streaming to your specific streams using the same region as the last stream, and it also surprisingly worked!

So I only have 2 guesses now:
 - You might have some issue with the video file or the way you are trying to stream; or
 - You hit some natural instability in our staging environment (it's currently "unmonitored"), hitting either a Mist instance, RabbitMQ or cluster that was unhealthy.

Either way, we can go through that tomorrow together, and I can send you some files and commands to try streaming this time. To get started setting up I'd suggest installing the raw [ffmpeg](https://www.ffmpeg.org) CLI in case you don't already have it, I think it's the most guaranteed way of doing this. On Mac I just installed it with brew, but you can also try using [go-livepeer](github.com/livepeer/go-livepeer)'s `install_ffmpeg` script

**Comment by victorges** [comment] 2021-11-09 23:43
Ohhh, I think I just found out what happened! The problem is simply that you updated your multistream targets while your stream was already active. Or at least that's what it seems like from a couple logs I saw in the API. At least on this stream (`3d97fdea-0094-40ae-9d04-9b9837b67064`), you seem to have streamed from 18:51:40Z to 20:11:25Z, while you only made changes to multistream targets between 19:03:27Z and 19:12:58Z.

We do not support editing the multistream targets of an ongoing stream. To make the change effective you need to stop the stream and start it again only after finalizing any multistream configurations. That explains why you didn't see multistream information in the stream health API output. The only thing that I do not know now is why your second stream (`43a6479b-3a73-4fdf-8784-36a4d6570e44`) was also showing up as active in the dashboard. In fact, it even seems to have been active even before (19:02:54Z) you configured multistream for the first time. Did you happen to have another process streaming to that other stream locally as well?

Also, if the configuration while the stream was active was really the issue, we might need to think about updating that notice in the multistream dialog about the changes not taking effect until the next session is started. Maybe it could be improved for further clarity as well. cc @pglowacky

**Comment by FullStackTiger** [comment] 2021-11-11 18:59
![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/da27cd27-5ffe-49a7-ad09-3a51caefbd47)
Finally I am getting the MultistreamBitrateSec, but I can't find ingestRate into the MultistreamBitrateSec obj.
Also I can't find ingestRate value on the multistream-metrics.zip you attached above, what am I missing?
@victorges

**Comment by victorges** [comment] 2021-11-11 20:02
@FullStackTiger there is actually no "ingest" rate for multistream targets, there could be mostly an "egest", "outbound" or "egress" rate instead. I think none of these terms are good though since they're not widely used in the industry AFAIK.

So @pglowacky @adamsoffer WDYT of renaming the whole graph to "Session Bitrate" and have the "ingest" word only as the label for the current data that we show [1]? 

i.e. In the graph below that Adam shared, replace "Session ingest rate" with "Session bitrate" and "Livepeer.com" with "Ingest".
![image](https://user-images.githubusercontent.com/1613383/141361057-b85c19f7-3e68-4ac1-a632-c8eefe680cd1.png)

Also just to be sure, the "Destionation #1/2" should actually be the names of the multistream targets, right? As shown in the dashboard. Could also consider composing it with the profile name like "{name} ({profile})" (e.g. `twitch.tv (720p)`) since the same target could be used in multiple "multistreams", and it's also useful to know the profile when inspecting bitrate.

[1] What we show is actually **transcoding** bitrate since it's measured from the broadcaster. But I think it's fine to keep calling it ingest while we don't have an ingest metric coming directly from mist.

**Comment by FullStackTiger** [comment] 2021-11-12 16:28
We need to check the Stream Health API again, seems it has some issues with the multistream targets yet.

I added one stream to the Multistream Targets, but the metrics.MultistreamBitrateSec[] from Stream Health API is getting 6 arrays. I thought it is one item(array) for each multistream target? @victorges @adamsoffer 
![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/273a779b-2e3b-4a14-8c1e-d12f312b2111)

![image.png](https://images.zenhubusercontent.com/616efed4bc03b82db7d9e3ae/653cd4d6-7009-4628-9ea2-d8baeb3bdf5b)

- Seems these 6 arrays(metrics.MultistreamBitrateSec[]) are pointing to one target stream(the dimensions's targetId is the same ), but the value of the last array is different.
- Another thing is the last field value, we thought the last field is basically a tuple containing the timestamp and the value of the last reading for that metric(`[unix millis timestamp, value]`).
so I am trying to get the X axis value using last[0] for the graph, these last[0]'s values are earlier dates like this:
`1636710003547(7 hours ago), 1636596549120(2 days ago)`
it is impossible to use this:

```
 {
    name: metric[0] - startTime,
    kbps: Math.round(metric[1] / 1000),
 }
```

What about do you think?

**Comment by victorges** [comment] 2021-11-12 16:41
Hey @FullStackTiger this happens because currently the stream health API does not clear values from previous sessions of the streams.

This wasn't too big of an issue since we didn't create new entries for different sessions, so we always overwrote any previous values. It is not the case for metrics though, se we have a couple dimensions in there with both the region and the media server (mist) instance where you are streaming to.

This causes the metrics to appear as if they are duplicate and also to have timestamps way back in the past, as you are noticing yourself. If we kept the API as is, you **would** have to compare the dimensions of the metrics and only pick the ones that correspond to the "extra data" in the `Active` condition. Told you the metrics are still kinda experimental 😆

But anyway, the great thing is that I have already written a fix for this! I am going to merge the pull request which has already been approved and you should be able to have a better experience in a few minutes already (plus you'll beta test the new logic, lmk of any issues)

**Comment by victorges** [comment] 2021-11-12 19:37
FTR: Merged the fix a little after the comment above. It's this one: https://github.com/livepeer/livepeer-data/pull/22

Should be in staging (livepeer.monster) already! Lmk if you have any issues.

**Comment by adamsoffer** [comment] 2021-11-12 19:40
> So @pglowacky @adamsoffer WDYT of renaming the whole graph to "Session Bitrate" and have the "ingest" word only as the label for the current data that we show [1]?

@victorges Good call. I'd be in favor of this.

**Closed as completed** 2022-03-22 17:56 UTC
